# hosts/nixos/default.nix
# ------------------------------------------------------------------------------------------------------------------------
# Main entry point for the host.
# All configuration is split into focused modules and imported here.
# Avoid putting logic in this file - it should read like a manifest.
# ------------------------------------------------------------------------------------------------------------------------
{ config, pkgs, vars, inputs, ... }:

let
  # Desktop shell module, picked from vars.desktopShell ("noctalia" | "dank" | "caelestia" | "end4-dots").
  # Only the selected shell's system-level module is imported, so the other shells' services
  # never start and don't fight over the compositor / lockscreen PAM entry.
  desktopShellModule =
    if vars.desktopShell == "noctalia" then ../../modules/desktop/noctalia.nix
    else if vars.desktopShell == "caelestia" then ../../modules/desktop/caelestia.nix
    else if vars.desktopShell == "end4-dots" then ../../modules/desktop/end4-dots.nix
    else { };
in
{
  imports = [
    # Hardware -----------------------------------------------------------------------------------------------------------
    ../../hardware-configuration.nix    # generated by nixos-generate-config

    # System modules -----------------------------------------------------------------------------------------------------
    #../../modules/system/nix.nix          # Source build stuff
    ../../modules/system/hardware.nix     # GPU, CPU microcode, firmware
    ../../modules/system/locale.nix       # timezone, locale, keyboard layout
    ../../modules/system/networking.nix   # NetworkManager, firewall, Tailscale, VPN
    ../../modules/system/audio.nix        # Pipewire, Bluetooth
    ../../modules/system/user.nix         # user account, sudo, groups
    #../../modules/system/self-repair.nix  # Automatic maintenance & self-healing
    ../../modules/system/security-hardening.nix  # Security & privacy hardening (AppArmor, sysctl, polkit, …)
    #../../modules/system/kernel-optimization.nix # Kernel compilation & performance tuning
    #../../modules/system/kernel.nix       # optimization with compiling everything possible
    ../../modules/system/boot.nix         # boot options

    # Desktop modules ----------------------------------------------------------------------------------------------------
    ../../modules/desktop/hyprland.nix  # Hyprland compositor (system-level)
    desktopShellModule                  # Selected shell (vars.desktopShell): noctalia / dank / caelestia

    # Package / service modules ------------------------------------------------------------------------------------------
    ../../modules/packages/base.nix        # core CLI tools
    ../../modules/packages/development.nix # editors, compilers, language runtimes
    ../../modules/packages/utilities.nix   # enhanced CLI tools: atuin, mise, zoxide, etc.
    ../../modules/packages/offline-content.nix # Kiwix, offline references
    ../../modules/packages/security.nix    # pentest / network analysis tools
    ../../modules/packages/creative.nix    # media production apps
    ../../modules/packages/gaming.nix      # Steam + gaming support
    ../../modules/packages/services.nix    # printing, Flatpak, misc services
  ];

  nixpkgs.config = {
    allowUnfree = true;
    permittedInsecurePackages = [
      "electron-36.9.5"
      "electron-39.8.10"
    ];
  };

  assertions = [
    {
      assertion = builtins.elem vars.desktopShell [ "caelestia" "noctalia" "dank" "end4-dots" ];
      message = "vars.desktopShell must be one of: caelestia, noctalia, dank, end4-dots";
    }
  ];

  # Nix settings - enable flakes and the new CLI globally
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store   = true;   # deduplicate store on every build
  };

  # Git - system-wide defaults; home-manager inherits these
  programs.git = {
    enable = true;
    config = {
      user.name  = vars.gitName;
      user.email = vars.userEmail;
    };
  };

  # XDG MIME associations - make the configured browser the default for all relevant types
  xdg.mime.defaultApplications = {
    "text/html"                = "${vars.browser}.desktop";
    "x-scheme-handler/http"    = "${vars.browser}.desktop";
    "x-scheme-handler/https"   = "${vars.browser}.desktop";
    "x-scheme-handler/about"   = "${vars.browser}.desktop";
    "x-scheme-handler/unknown" = "${vars.browser}.desktop";
  };

  system.stateVersion = "25.05";
}
